const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  SALES: 'SALES'
};

const DEFAULT_PERMISSION_MATRIX = {
  TENANT_READ: ['OWNER', 'ADMIN'],
  USER_MANAGE: ['OWNER', 'ADMIN'],
  PERMISSION_CONFIG_MANAGE: ['OWNER', 'ADMIN'],
  LEAD_READ: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  LEAD_WRITE: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  STAGE_MANAGE: ['OWNER', 'ADMIN', 'MANAGER'],
  TASK_READ: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  TASK_WRITE: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  ACCOUNT_READ: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  ACCOUNT_WRITE: ['OWNER', 'ADMIN', 'MANAGER'],
  CONTACT_READ: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  CONTACT_WRITE: ['OWNER', 'ADMIN', 'MANAGER'],
  NOTE_READ: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  NOTE_WRITE: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  ACTIVITY_READ: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  SEARCH_READ: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  SAVED_FILTER_READ: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  SAVED_FILTER_WRITE: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  OPPORTUNITY_READ: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  OPPORTUNITY_WRITE: ['OWNER', 'ADMIN', 'MANAGER'],
  DASHBOARD_READ: ['OWNER', 'ADMIN', 'MANAGER', 'SALES'],
  AUDIT_READ: ['OWNER', 'ADMIN']
};

module.exports = {
  ROLES,
  DEFAULT_PERMISSION_MATRIX
};
